services:
  - type: web
    name: vynk-signaling
    env: node
    plan: free
    region: oregon # ou singapore se mais próximo do BR (latência)
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000 # Render injeta PORT
      - key: CLIENT_URL
        value: https://vynk-dun.vercel.app
      - key: CLOUDFLARE_TURN_API_TOKEN
        sync: false
      - key: CLOUDFLARE_TURN_KEY_ID
        sync: false
